apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-node-app-express
spec:
  ports:
    # Accept traffic sent to port 8000 on the Service
    # and forward it to port 3000 on the Pod containers
    - name: http
      port: 8000         # Port exposed by the Service
      targetPort: 3000   # Port on which Node.js app is running inside the Pod
  selector:
    
    app: node-app-express # must match the label of the Pods / template in deployment-node-app.yml  as service select the matching pod container
    # Loadbalance traffic across Pods matching this label selector  
  # and expose the Service outside the cluster to the internet
  # with an External IP address using an external load balancer 
  # Only supported by some cloud providers by some cloud providers
  type: LoadBalancer # Options: ClusterIP (Default), NodePort, LoadBalancer