apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-file-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-file-app
  template:
    metadata:
      labels:
        app: node-file-app
    spec:
      containers:
      - name: node-file-app
        image: 080bct12/node-file-app:02   # here if we dont use any persistence volume there is chance of data lost
        


---

apiVersion: v1
kind: Service
metadata:
  name: service-node-file-app
spec:
  ports: 
    - name: http 
      port: 8080
      targetPort: 3000
  selector:
    app: node-file-app
  type: LoadBalancer