# MongoDB Deployment and Service Config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo:latest

---

apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: mongo-app
  ports: # from here added for mongo port
    - name: tcp  # optional name ,can be helpful when working with multiple pods
      port: 27017
      targetPort: 27017
   # Client → K8s Service (port 27017) → Pod (targetPort 27017) → MongoDB
      # MongoDB → Pod → Service → Client